### ISSUE TITLE
Pantheon workflow?

### ISSUE THREAD

**Issue by mmynsted** [kalamuna/kalaboxv1#133]
I followed the instructions for using Kalabox with [Pantheon](https://www.getpantheon.com) as described [here](https://github.com/kalamuna/kalaboxv1/wiki/Getting-Started-With-Kalabox-V1).

The pantheon based site worked fine inside my local Kalabox, at least until [issue 132](https://github.com/kalamuna/kalaboxv1/issues/132).
I then added and configured modules, created content, etc. in the local Kalabox version of the site.
I committed my local changes and pushed them to the remote pantheon git repo with applicable git pushes.  

There are two parts of the Kalabox - Pantheon workflow for which I am unclear.
- **_How do I ensure that database and file changes are pushed up to pantheon?**_  It appears that commits pushed to Pantheon are reflected in the pantheon `dev` environment, if what is shown in the git log, on the pantheon dashboard, is mirrored in the sources for the `dev` environment.  Described [here](http://helpdesk.getpantheon.com/customer/portal/articles/361247#push-changes-to-pantheon). It does not appear that database changes would be loaded without an explicit pantheon database import.
- **_How do I ensure that modules managed by pantheon, such as Drupal core, are merged into the local Kalabox hosted version of the site?**_  Kalabox has a refresh mechanism for refreshing the database, the sources or both from the pantheon `dev` version of the site.  Unless there is some way to move the local changes up to pantheon, it seems this would destroy/replace the work performed locally.

**Comment by pirog** [comment]
1. @mmynsted, so the normal "best practices" drupal workflow is to only push up code. that said we realize that pushing updates via the database is a common use case. for this sort of thing the best thing is probably to go to `php.kala` in your browser. export your database with `phpmyadmin` and then import it directly into pantheon... along with pushing up your new code with git. files can be imported in a similar way to teh database. just make an archive and import. a good way to get around this is to use the features module which allows you to export DB config into code so that you can deploy it with git. 
2. the best way to get updates that are merged into your code via the dashboard on your local kalabox is to just run `git pull` from inside your webroot or to use the kalabox UI to "refresh" the site's code. for this you will only want to pull down the code part as refreshing teh database, as you surmise, will wipe any changes you made that are not yet in code.

**Comment by mmynsted** [comment]
Ok.  The `features` module sounds like a good answer for exporting the DB config.  Using `git pull` sounds like the right way to merge in upstream code changes.  Also never pulling down database changes and only rarely pushing up database changes sounds like a good plan.  Thank you.
