### ISSUE TITLE
Swap installer to install docker dependencies

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalaboxv1#53]
We want this to be the most cross platform as possible. Boot2docker will get us most of the way. Install will look something like this
1. Check for VB, install if min version not met
2. Install boot2docker tools, use our config, spin up docker VM
3. instantiate docker shell 

We will need to figure out a cross platform way to get and store user creds. Should try to do #46 here if possible.

**Comment by mikemilano** [comment]
https://github.com/mikemilano/kalabox/compare/docker_install?expand=1

There's no 2x branch yet, but I wanted to get some feedback before i did a PR anyway.
- Vagrant removed from installer
- boot2docker check/installer
- kalastack-docker check/installer
- boot2docker image check/installer
- power on vm

Notes:
- It will just work on OSX right now.
- For some reason I lost the auto redirect to `/install` (probably something simple I'll find), so right now I set `"toolbar": true` in `package.json` so I could manually hit the installer.
- I completely removed VB & boot2docker and it successfully installed.
- `kalastack-docker` is installed via `git pull`. Not sure the preferred method of handling that.
- Added a `HOME` var because `boot2docker init` needs to run from there. `exec()` didn't seem to like using the string `$HOME`.
- I didn't touch the progress meter stuff so it's not pretty. You can get a good idea of what is happening in the terminal.

**Comment by pirog** [comment]
oh wow! this is great. im going to spin up a 2.x branch after i write some @mikemilano inspired docs for everybody but i will test this out ASAP

**Comment by mikemilano** [comment]
The latest commit fixes the install redirect and reverted the toolbar value. I think we just need to decide running a `git pull` on `kalastack-docker` in the install is OK and then work on the progress status. It should install everything now though. It takes a while when starting from scratch.

**Comment by pirog** [comment]
i dont think we can assume that git is installed on the host machine. i know we were just downloading the archive an untarring with kalastack. 

this is going to be great and helpful when we get to the installer on V2. 

In the kalastack-docker repo i produced some basic install scripts for OSX/Windows and was thinking about the merit of a different installer implementation for V2 where we use something like this https://www.npmjs.org/package/applescript (but cross platform for vb script/bash) and just have node execute the scripts directly as sudo/admin. I know the installer in V1 is really error prone, lots of moving parts and at the end of the day its basically just a heavy wrapper around shell commands anyway. Thought just going directly to a script may reduce complexity and improve stability. 

Anyway that isn't super relevant to this exact issue but thought id throw it out there.
