### ISSUE TITLE
Figure out how to handle /etc/hosts

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalaboxv1#56]
Node has a good cross platform module for handling this but it requires the node binary. We are using node-webkit and just packaging in the node binary for this one thing. It's pretty jank and we should find a better solution.

**Comment by gremy** [comment]
Would this python script be good? We can compile it as a binary cross platform, so python would not be required on the host machine.
https://github.com/jasonvanzin/hostfileupdate/blob/master/hostfileupdate.py

**Comment by mikemilano** [comment]
Another option might be a DNS service running in Docker. I tested with `dnsmasq`. This route would stay out of the way of the user's /etc/hosts file.

dnsmasq has an option to serve records from a host file, so this example uses that method to keep things simple. 

On the Docker host, setup a custom hosts file:

```
sudo mkdir /etc/kalabox
sudo touch /etc/kalabox/hosts
```

Then create a dnsmasq image:

```
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y -q dnsmasq

EXPOSE 53
# /etc/kalabox will be a volume on the host with the same path
CMD ["/usr/sbin/dnsmasq", "-k", "-H", "/etc/kalabox/hosts"]
```

Build and run it

```
docker build -t kalabox/dnsmasq .
docker run -d --name dnsmasq -p 53:53/udp -v /etc/kalabox:/etc/kalabox:rw kalabox/dnsmasq
```

Now the docker host would be running a DNS server that can be managed from a host file. Being that the host file is in /etc/kalabox/hosts, and it's running as a name server, there's no worry about conflicting with the user's own host records.

The container does need to be restarted to pick up changes in the kalabox host file. There may be a better way to manage hosts with dnsmasq too; this was just an easy way to test the service concept without learning everything about dnsmasq.

I've tested this on OSX by adding `1.3.3.7` to the DNS tab in my network config (resolve.conf doesn't pick up on OSX).  `nslookup` resolves the custom entries but `ping` does not resolve. I'm not sure why, but if this route makes sense, we can investigate it further.

**Comment by pirog** [comment]
@mikemilano i am definitely intrigued by this approach. we are currently using the "hostile" node plugin to manage users hosts files but for a couple reasons this approach leaves a lot to be desired.
1. needs to be run as an admin
2. because of 1. we need to execute it as a script with the node binary (may be another way to do this)
3. because we are using node-webkit we cant actually assume the node binary exists so we are shipping kalabox with the node binary which is gross 
4. i dont think (but could be wrong) that you can use the node-webkit binary to execute node commands a la the node binary but it seems like you should be able to. 

Anyway 1-4 basically suck and are a huge PITA. 

I like the idea of not messing with the users hosts file a lot but presumably we would still need admin perms to add the DNS entry to OSX and to resolve.conf in debian and NO IDEA how that would work on Windows... Am i wrong in that assumption? 

is there anyway we could roll with an approach that did not require admin perms or messing with the users resolve.conf (or equiv)? I guess one nice thing is we would theoretically only need to add the entry to resolve.conf once and if we need admin perms to set the whole box up we could just do it then?

**Comment by pirog** [comment]
@gremy how is this python binary approach any different than what we are already doing in V1 with the node binary and hostile mod?

**Comment by gremy** [comment]
@pirog After you compile the binary you don't need to have python or node installed on the host machine. You can simple execute the binary, which is very small, so no overhead.

**Comment by pirog** [comment]
@gremy good to know. definitely an option.

**Comment by tizzo** [comment]
I think what might be a much stronger option would be to use [avahi](http://avahi.org/).  Zeroconf will work right out of the box for all macs,
requires one lil' package to be installed on linux, and is pretty easy to
get up and running on windows (I'm told; I haven't really run windows since
2005).

Unfortunately avahi doesn't let you just add cnames to a conf file so there
are python projects for doing it via the [dbus api](https://github.com/airtonix/avahi-aliases).  It's actually pretty straight
forward.  I have a node.js module almost finished - just sorting out a bug
in data type casting.  I think I'll be creating an issue on [the dbus module](https://www.npmjs.org/package/dbus-native) I'm building off of shortly,
I'll try to link that back here.

With this approach when the VM is on it advertises it's own hostnames and
they just work from the host like magic.  If the VM goes away the hostname
goes away through the magic of multicast DNS.  You don't need them to
change their DNS service and you don't need to touch any on either client
or host.  We'd just need an agent to somehow be told the list of sites
available (could be a set of conf files or could be transmitted to a client
inside the VM (probably running inside a separate container to make @Pirog
smile).

**Comment by mikemilano** [comment]
@pirog It's my understanding that resolv.conf is not used with OSX, despite the fact that it's there. I had to manually add the DNS entry in system -> network -> [interface] -> advanced -> dns. Linux would obviously work, but I'd need to look into what it takes to do that programmatically in Windows & OSX.

What brought me back to the topic this morning was a good docker/dnsmasq example published this morning: http://wiredcraft.com/posts/2014/07/30/dns-and-docker-containers.html . I like how DNS is passed into the run command and the dns for each app is hosted in a separate file. This file could actually represent the site, with DNS for all the containers inside.

At one level we have the apps knowing about themselves, and another is the user's system knowing about the web host. The dns format could be `<role>.<sitename>`, and perhaps the web role would also have the main site entry.  i.e. `mysite` (same destination as `nginx.mysite`), `nginx.mysite`, `db.mysite`, `php.mysite`)

We could pass in the hostname of each role, as environment variables to the `docker run` command as well as use the same naming convention for the `docker run` `--name` argument.

@tizzo not ignoring the avahi suggestion or suggesting dnsmasq is better yet, I haven't had a chance to check it out in detail yet.  That said, my only thoughts are that since we're using Docker already, there may be value to run any service dependencies in docker rather at the main system level.

**Comment by pirog** [comment]
this is all great stuff. 

@mikemilano if you want to research what the dnsmasq implementation would entail in windows/osx i can try out @tizzo's suggestion on windows and see what exactly that entails. I definitely like a lot of the ideas in that article and +1 on `<role>.<sitename>`... thats something that i wold love to see vs the less UX friendly docker host/ip randomization. That said, we could also do similar things in the the @tizzo approach and having a node client implementation could be helpful. 

At the end of the day i think the least complex implementation is how we want to roll.

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/issues/20
