### ISSUE TITLE
Unknown configuration section 'hostsupdater'

### ISSUE THREAD

**Issue by chrowe** [kalamuna/kalaboxv1#81]
OSX 10.9.4
Kalabox Version: 1.0-beta7
1. Installed and was working.
2. After running for a few days it showed an error in the GUI. I closed if before noting the error. ([This error from the log](https://gist.github.com/chrowe/9de4b45bab99ab0734da) may correspond but not sure)
3. GUI starts up fine but when I click the "Start" button I get

> Looks like the box wasn't quite ready. Please try again in a moment. If the problem persists, please let us know at errors@kalamuna.com.

Log shows

> warn: Command failed: There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> Vagrant:
> - Unknown configuration section 'hostsupdater'.

**Comment by reynoldsalec** [comment]
This happened to me too the other day, somehow I accidentally uninstalled the hostsupdater vagrant plugin. To get things going again if you "cd ~/.kalabox/kalastack" and run "vagrant plugin install vagrant-hostsupdater" it should fix things up.

I think it's possible that this happened to me because when Kalabox came up, I accidentally hit "Box Me" (since it flashed the install screen for a second before going to the dashboard) and began trying to install dependencies over my Kalabox, something similar (or anything out of the ordinary) happen to you @chrowe?

**Comment by chrowe** [comment]
That fixed my issue. Thanks

It was running when I first got the error. I do notice the "Box Me" screen flashes but don't think I ever touched it.

**Comment by pirog** [comment]
@chrowe yeah the "box me" screen does sometimes flash for a bit. This was a result of us moving from AppJS to NodeWebkit but still using Express which node-webkit doesnt really like. We should figure out a way to fix that since its confusing and annoying. That issue is posted here
https://github.com/kalamuna/kalabox/issues/41

For the plugin... this is troublesome. @reynoldsalec maybe we can add a check to box start that makes sure the plugin is actually installed in case this weirdness happens again?
